#!/bin/bash
var1=$(zenity --forms --title="Welcome to GLS Audit" --text="Enter details" \
   --add-entry="Organization Name" \
   --add-entry="Lab Name/Number. If any" \
   --add-entry="System Number like 1,2,3.." \
   --add-password="Password" \
   --add-calendar="Select Date")
var2=$(echo $var1|cut -d'|' -f4)
var3=$(echo $var1|cut -d'|' -f3)
var4=$(echo $var1|cut -d'|' -f1)
mkdir /root/output
(echo "###################Hardware Details>#####################################" 

echo "========================Sys Info=========================================="
echo "SYSTEM-MANUFACTURER: $( dmidecode -s system-manufacturer)"
echo "SYSTEM-PRODUCT-NAME: $( dmidecode -s system-product-name)"
echo "SYSTEM-SERIAL-NUMBER: $( dmidecode -s system-serial-number)"
echo "SYSTEM-UUID: $( dmidecode -s system-uuid)"
echo "SYSTEM-FAMILY: $( dmidecode -s system-family)"

echo "======================Baseboard Info======================================"
echo "BASEBOARD-MANUFACTURER: $( dmidecode -s baseboard-manufacturer)"
echo "BASEBOARD-PRODUCT-NAME: $( dmidecode -s baseboard-product-name)"
echo "BASEBOARD-SERIAL-NUMBER: $( dmidecode -s baseboard-serial-number)"

echo "======================Chasis Info========================================="
echo "CHASSIS-MANUFACTURER: $( dmidecode -s chassis-manufacturer)"
echo "CHASSIS-TYPE: $( dmidecode -s chassis-type)"
echo "CHASSIS-SERIAL-NUMBER: $( dmidecode -s chassis-serial-number)"
echo "CHASSIS-ASSET-TAG: $( dmidecode -s chassis-asset-tag)"

echo "======================CPU Info============================================"
echo "CPU-VERSION: $( dmidecode -t processor| grep Version |awk '{$1=""; print $0}')"
echo "CPU-FAMILY: $( dmidecode -t processor| grep 'Family:' |awk '{$1=""; print $0}')"
echo "MAX-SPEED: $( dmidecode -t processor| grep 'Max Speed:' |awk '{$1=$2=""; print $0}')"
echo "CORE-COUNT:$( dmidecode -t processor| grep 'Core Count' |awk '{$1=$2=""; print $0}')"
echo "THREAD-COUNT:$( dmidecode -t processor| grep 'Thread Count' |awk '{$1=$2=""; print $0}')"

echo "======================Memory Info========================================="
echo "$( lshw -short -C memory)"

echo "======================Disk Info==========================================="
echo "$( lshw -short -C disk)"

echo "=====================Network Info========================================="
echo "$( lshw -short -C network)"

echo "=====================Monitor Info========================================="
echo "SCREEN-RESOLUTION: $(xrandr |awk '$0 ~ "*" {print $1}')"
echo "##########################################################################" 
echo "Information generated on $(date)"
) > /root/output/$var4-$var3-$(dmidecode -s system-manufacturer).out
git clone https://github.com/gls-audit/gls-audit-output -q
git config --global user.email "audit.gmail.com"
git config --global user.name "Audit"
cp -rf /root/output/$var4-$var3-$(dmidecode -s system-manufacturer).out /root/gls-audit-output/
cd /root/gls-audit-output;git add /root/gls-audit-output
cd /root/gls-audit-output;git commit  -m "$(date)" -q
cd /root/gls-audit-output;git push https://gls-audit:$var2@github.com/gls-audit/gls-audit-output  
if [ $? -eq 0 ]; then
zenity --info --title="Fetching completed" --text="Thanks for your patience.Shutdown and move to next." --no-wrap
rm -rf /root/gls-audit-output	
else
rm -rf /root/gls-audit-output	
zenity --error --title="Fetching Failed" --text="May be Internet connectivity or Password issue.Retry..... Or Copy file from "/root/output" and mail it." --no-wrap
fi
#echo -e "\x1B[31m Information generated on $(date) \x1B[0m"
#echo -e "\x1B[31m Thanks for your patience.You can poweroff and go to next machine \x1B[0m"

#echo "Information generated on $(date)"
#echo "Thanks for your patience.You can poweroff and go to next machine"
